services:
  web:
    image: nginx
    ports:
      - 8080:80
    restart: always  # <-- reinício automático incluído
    depends_on:
      - banco

  banco:
    image: mariadb
    restart: always  # <-- reinício automático incluído
    environment:
      MARIADB_USER: sa
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: demodb
      MARIADB_ROOT_PASSWORD: 12345
    expose:
      - 3306
    volumes:
      - ~/data:/var/lib/mysql
